import { Inter as FontSans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

import { ThemeProvider } from "@/components/theme-provider";
import { Icons } from "@/components/icons";
import { ModeToggle } from "@/components/change-mode";
import { Sidebar } from "@/components/sidebar";


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

// Font files can be colocated inside of `pages`
const fontHeading = localFont({
  src: "../../assets/fonts/CalSans-SemiBold.woff2",
  variable: "--font-heading",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "  bg-background  font-sans antialiased min-h-screen  ",
          fontSans.variable,
          fontHeading.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <div className="md:grid grid-cols-7 lg:grid-cols-11 overflow-hidden max-h-screen">
            <Sidebar  />
            {children}
            </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
