import { Inter as FontSans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

import { ThemeProvider } from "@/components/theme-provider";
import { Icons } from "@/components/icons";
import { ModeToggle } from "@/components/change-mode";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

// Font files can be colocated inside of `pages`
const fontHeading = localFont({
  src: "../../assets/fonts/CalSans-SemiBold.woff2",
  variable: "--font-heading",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "  bg-background font-sans antialiased min-h-screen  ",
          fontSans.variable,
          fontHeading.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          
            
            <header className="flex items-center justify-between border-b p-3 px-12">
              <nav className="flex  text-3xl items-center font-semibold">
                <Icons.logo className=" scale-110 invert dark:invert-0  transition-all duration-150" />
              </nav>
              <nav className="flex items-center  ">
                <ModeToggle />
              </nav>
            </header>
            {children}
          
        </ThemeProvider>
      </body>
    </html>
  );
}
